apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argus
resources:
  - ../../base
replicas:
  - name: argus-api
    count: 1
  - name: argus-frontend
    count: 1
  - name: argus-worker
    count: 1
  - name: argus-event-consumer
    count: 1
images:
  - name: ARGUS_BACKEND_IMAGE
    newName: REPLACE_WITH_BACKEND_REPOSITORY
    newTag: REPLACE_WITH_IMAGE_TAG
  - name: ARGUS_FRONTEND_IMAGE
    newName: REPLACE_WITH_FRONTEND_REPOSITORY
    newTag: REPLACE_WITH_IMAGE_TAG
patches:
  - path: delete-ingress.yaml
  - path: delete-hpa.yaml
  - path: delete-eval-cronjob.yaml
  - path: serviceaccount.yaml
  - path: configmap.yaml
