apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argus
resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - api.yaml
  - frontend.yaml
  - worker.yaml
  - kafka-topic-bootstrap.yaml
  - event-consumer.yaml
  - eval-cronjob.yaml
  - ingress.yaml
  - hpa.yaml
